---
name: Stackable Build Pipeline

on:
  push:
    branches:
      - main
      - staging
      - trying
      - "renovate/**"
    tags:
      - "*"
  pull_request:


jobs:
  run_rustfmt:
    name: Run Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@01aecccf739ca6ff86c0539fbc67a7a5007bbc81 # renovate: tag=v2.1.0
      - uses: actions-rs/toolchain@8e603f32c5c6eeca5b1b2d9d1e7464d926082f1d # tag=v1.0.0
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
          override: true
      - uses: actions-rs/cargo@eadeb9d8b98f01d4d584ac7b4124ab74116e52db  # tag=v1.0.0
        with:
          command: fmt
          args: --all -- --check
